version: '3'

services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: tiptop_db
      POSTGRES_PASSWORD: root
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  api:
    build: ./f2i-project-Api
    ports:
      - "3001:3001"
    depends_on:
      - db

  frontend:
    build: ./f2i-project-front
    ports:
      - "80:80"
    depends_on:
      - api

volumes:
  pgdata:
