version: '3'

services:
  db:
    image: postgres:11.22-alpine3.18
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: tiptop_db
      POSTGRES_PASSWORD: root
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  api:
    image: ousama4567/f2i-project-api:release
    ports:
      - "3002:3001"
    depends_on:
      - db

  frontend:
    image: ousama4567/f2i-project-front:release
    expose:
      - "3000"
    depends_on:
      - api

  nginx:
    image: nginx:alpine
    ports: 
      - "80:80"
    depends_on:
      - frontend
    volumes:
      - ./f2i-project-front/nginx.conf:/etc/nginx/nginx.conf:ro

volumes:
  pgdata:
